### ISSUE TITLE
在运行main.py的时候产生了一个bug

### ISSUE THREAD

**Issue by wpy297** [ZZCrazy00/DPI#1]
bug的具体细节如下：
python main.py
664 445
2926
SP
  0%|                                                                      | 0/1000 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/wupeiyuan/AI_Test2024/DPI/main.py", line 46, in <module>
    result = train_func(args, train_loader, val_loader, test_loader, model, optimizer, loss_fn)
  File "/home/wupeiyuan/AI_Test2024/DPI/utile.py", line 151, in train_func
    result = test_model(test_loader, model)
  File "/home/wupeiyuan/anaconda3/envs/myenv1/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/wupeiyuan/AI_Test2024/DPI/utile.py", line 127, in test_model
    logits = model(data, sample_indices, links, indices, target='test')
  File "/home/wupeiyuan/anaconda3/envs/myenv1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'target'

修改这个参数相关内容又会触发早停机制，想请教一下这一部分，谢谢！

**Comment by ZZCrazy00** [comment]
logits = model(data, sample_indices, links, indices)
抱歉，上传代码时没检查仔细，去掉target这个参数就好。
关于早停机制，我不太明白你的问题。

**Comment by wpy297** [comment]
是这样的，我尝试过去掉target这个参数，但是去掉这个参数之后，到第10个epoch就退出训练了，也就是说这连续的10个epoch并没有改善。所以我想问一下是不是别的地方还有什么问题我没有注意到.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月28日(星期二) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZZCrazy00/DPI] 在运行main.py的时候产生了一个bug (Issue #1)














 
logits = model(data, sample_indices, links, indices)
 抱歉，上传代码时没检查仔细，去掉target这个参数就好。
 关于早停机制，我不太明白你的问题。

**Comment by ZZCrazy00** [comment]
因为early_stop这个参数设置的是10，你可以打印看看每轮的测试结果，或者把early_stop设置的更大点

**Comment by wpy297** [comment]
我懂了，谢谢你的回答




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月28日(星期二) 中午11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZZCrazy00/DPI] 在运行main.py的时候产生了一个bug (Issue #1)














 
因为early_stop这个参数设置的是10，你可以打印看看每轮的测试结果，或者把early_stop设置的更大点

**Comment by wpy297** [comment]
main.py中：
parser.add_argument('--dataset_name', type=str, default='davis',
                    choices=['BindingDB', 'davis', 'enzyme', 'gpcr', 'ic', 'nr'])
parser.add_argument('--num_test', type=float, default=0.2, help='ratio of test datasets')
parser.add_argument('--ratio', type=float, default=1, help='ratio of positive samples and negative samples')
parser.add_argument('--task', type=str, default='SD', choices=['SD', 'ST', 'SP'])
时，运行产生bug：
Traceback (most recent call last):
  File "/home/wupeiyuan/AI_Test2024/DPI/main.py", line 64, in <module>
    print_result(all_result)
  File "/home/wupeiyuan/AI_Test2024/DPI/main.py", line 54, in print_result
    metric_values[j].append(float(val[-6:]))
ValueError: could not convert string to float: 'cc:nan'
同时在ic-SD、davis-ST、ic-ST这几种情况下也产生了同样的bug。
