### ISSUE TITLE
在运行main.py时有时候会出现ValueError

### ISSUE THREAD

**Issue by wpy297** [ZZCrazy00/DPI#2]
bug的具体细节如下：
main.py中：
parser.add_argument('--dataset_name', type=str, default='davis',
choices=['BindingDB', 'davis', 'enzyme', 'gpcr', 'ic', 'nr'])
parser.add_argument('--num_test', type=float, default=0.2, help='ratio of test datasets')
parser.add_argument('--ratio', type=float, default=1, help='ratio of positive samples and negative samples')
parser.add_argument('--task', type=str, default='SD', choices=['SD', 'ST', 'SP'])
时，运行产生bug：
Traceback (most recent call last):
File "/home/wupeiyuan/AI_Test2024/DPI/main.py", line 64, in
print_result(all_result)
File "/home/wupeiyuan/AI_Test2024/DPI/main.py", line 54, in print_result
metric_values[j].append(float(val[-6:]))
ValueError: could not convert string to float: 'cc:nan'
同时在ic-SD、davis-ST、ic-ST这几种情况下也产生了同样的bug。

感谢作者花时间看我的提问！

**Comment by ZZCrazy00** [comment]
因为保存的指标中存在nan值，你可以看看模型训练每轮的输出结果。
